### PR TITLE
Update to the C# code

### PR DESCRIPTION
**Pull request by MarkAtRamp51**
The C# example, will draw on the Filtering row so I'm suggesting a change to fix this.  However, I've only been using the controls for 1 day, so there might be a better way.

### CODE REVIEW

**Comment by icom85** [comment]
Hello,

The check as it is at the moment is sufficient and the custom painting logic will only be executed for the data cells.

**Comment by MarkAtRamp51** [comment]
Than maybe it's just a problem with the Trial version of the Winforms UI library, because you can see here, the behavior isn't as you describe.   Here is a screen shot and the code without the restriction for GridFilterRowElement.

griderror
`        private void UiConditionsGrid_CellPaint(object sender, GridViewCellPaintEventArgs e)
        {
            GridDataCellElement dataCell = e.Cell as GridDataCellElement;
            
            if (dataCell != null && dataCell.ColumnInfo.Name == "NewStatus")
            {
                string value = (string)dataCell.Value;

                if (!string.IsNullOrWhiteSpace(value))
                {
                    Brush brush = Brushes.Red;
                    Size cellSize = e.Cell.Size;
                    using (Font font = new Font("Segoe UI", 17))
                    {
                        e.Graphics.DrawString("*", font, brush, Point.Empty);
                    }
                }
            }
        }`

**Comment by icom85** [comment]
Hello,

I managed to reproduce the result on your end. We will update our documentation code project the following way:

````C#
void radGridView1_CellPaint(object sender, Telerik.WinControls.UI.GridViewCellPaintEventArgs e)
{
    if (e.Cell != null  && e.Cell.RowInfo is GridViewDataRowInfo  && e.Cell.ColumnInfo.Name == "UnitPrice")
    {
        double value = Convert.ToDouble(e.Cell.Value);
        if (value == 0)
        {
            return;
        }

        Brush brush = value < 20 ? Brushes.Red : Brushes.Green;
        using (Font font = new Font("Segoe UI", 17))
        {
            e.Graphics.DrawString("*", font, brush, Point.Empty);
        }
    }
}

**Comment by MarkAtRamp51** [comment]
Cool man. Just trying to help out.

**Pull request closed without merging**
