### PR TITLE
Create dataentry-customize-editor-controls-layout.md

### PR DESCRIPTION
**Pull request by LanceMcCarthy**
Add tutorial KB for rearranging `RadDataEntry` item controls, arose from **Ticket 1167646**

_Note:_ 
I'm not sure which branch to submit the PR to, so I chose master. I'll let you guys change the base fork if necessary and will submit to that branch in the future.

### CODE REVIEW

**Comment by LanceMcCarthy** [comment]
Thanks for the update!

Since I'll be creating VB code, how do I properly use the 'region' snippet that will render the C#/VB tabs?

**Comment by DKaramfilov** [comment]
The region contains the path to the file where the code is and the actual region name. We are using a Visual Studio solution that contains the code snippets and can be built at any time. This way we are sure that the entire code is valid and can be compiled. The solution is located here: $/WinForms_Scrum/Development/Help/DocumentationCode

You can examine the structure and the regions. There is a tool that takes the code and places it in the docs when the docs build is executed.

If you cannot access it just remove the region tags and use an inline code with the following format:
````C#
//code

````
````VB.NET
'code

````

This way the tabbed code functionality will work as expected.

**Comment by LanceMcCarthy** [comment]
Okay thanks for the info. I'll take the backquote approach as it's one I use frequently.

Since it will be rendered in the code block, how do I make sure the two code blocks get rendered into the same C#/VB section?

Does the renderer see two code blocks one C#  and one VB and knows to combine them?

Can I use this syntax:


image

**Comment by DKaramfilov** [comment]
It interprets it as a code in my previous post and the exact syntax cannot be seen. I have attached a small file that shows the syntax:
[code.txt](https://github.com/telerik/winforms-docs/files/2038874/code.txt)

**Pull request merged**
